#+title: Lys og bølger
#+subtitle: Inspirationsfase - Simuleringer
#+author: Jacob Debel
#+date: Fysik C & B
# Themes: beige|black|blood|league|moon|night|serif|simple|sky|solarized|white
#+reveal_theme: night
#+reveal_title_slide: <h2>%t</h2><h3>%s</h3><h4>%a</h4><h4>%d</h4>
#+reveal_title_slide_background:
#+reveal_default_slide_background:
#+reveal_extra_options: slideNumber:"c",progress:true,transition:"slide",navigationMode:"default",history:false,hash:true
# #+reveal_extra_attr: style="color:red"
#+options: toc:nil num:nil tags:nil timestamp:nil ^:{}

* Introduktion
I mangel på ledige fysiklokaler anvender denne inspirationsfase en række simuleringsprogrammer i stedet for rigtigt forsøgsudstyr, samt lidt klippe-klister-fysik. :) 

* Lys og optiske fænomener
#+reveal_html: <div style="font-size: 50%;">
#+reveal_html: <div style="display: grid; grid-template-columns: 40% auto;">
#+reveal_html: <div>
- *Første runde*

  Det gælder om at *lege*. I skal eksperimentere med de i alt seks forskellige simuleringer og observere, hvad der sker med lysetstrålerne og bølgerne igennem deres passager i de forskellige opstillinger. Der er ingen regler for, hvad I skal gøre med simuleringerne, men I skal udforske dem så meget som muligt.

#+reveal_html: </div>

#+reveal_html: <div>
- *Anden runde*

  I denne runde skal I koncentrere jer om én af forsøgsopstillingerne/simuleringerne. I skal sørge for, at der er en eller flere fysiske størrelser, der kan måles på, og som kan ændres direkte eller indirekte igennem simuleringen. Det kan f.eks. være vinkler, farver, udsving, tider og mønstre.

  I skal aflevere en skriftlig sproglig beskrivelse af, hvad der sker med lyset/bølgerne undervejs i jeres valgte forsøg/simulering. Ingen brug af bøger eller internetkilder, kun jeres egne sproglige beskrivelser. Det er tilladt at tage screenshots af simuleringerne og tegne og forklare ud fra dem. *Jeres beskrivelser skal afleveres på lectio under den tilhørende opgave i pdf-format.*
#+reveal_html: </div>
#+reveal_html: </div>
#+reveal_html: </div>

* Simuleringer

I begge simuleringer skal I eksperimentere med alle dele.

** Afbøjning af lys
#+begin_export html
<iframe src="https://phet.colorado.edu/sims/html/bending-light/latest/bending-light_da.html"
        width="800"
        height="500"
        allowfullscreen>
</iframe>
#+end_export
** Bølgeinterferens
#+begin_export html
<iframe src="https://phet.colorado.edu/sims/html/wave-interference/latest/wave-interference_da.html"
        width="800"
        height="500"
        allowfullscreen>
</iframe>
#+end_export
