#+title: Lys og bølger
#+subtitle: Inspiration - Eksperimenter 
#+author: Jacob Debel
#+date: Fysik C & B
# Themes: beige|black|blood|league|moon|night|serif|simple|sky|solarized|white
#+reveal_theme: night
#+reveal_title_slide: <h2>%t</h2><h3>%s</h3><h4>%a</h4><h4>%d</h4>
#+reveal_title_slide_background:
#+reveal_default_slide_background:
#+reveal_extra_options: slideNumber:"c",progress:true,transition:"slide",navigationMode:"default",history:false,hash:true
# #+reveal_extra_attr: style="color:red"
#+options: toc:nil num:nil tags:nil timestamp:nil ^:{}



* Lys og optiske fænomener

#+reveal_html: <div style="font-size: 60%;">
- I skal undersøge synligt lys. I får udleveret lyskilder og diverse forsøgsudstyr. Jeres opgave er at eksperimentere med forskellige forsøgsopstillinger, som I selv finder på.

- Det gælder om at lege. I skal afprøve forskellige forsøgsopstillinger og observere, hvad der sker med lysstrålerne igennem deres passage i de forskellige opstillinger. Dette får I ca. 45 minutter til.

- I de næste 45 minutter udvælger I den mest interessante forsøgsopstilling.
    I skal sørge for, at der er nogle fysiske størrelser, som I kan måle på. Det kan f.eks. være vinkler, farver, udsving og tider.

- I skal beskrive, hvad der sker med lyset undervejs i jeres valgte forsøg. *Dette skal I aflevere skriftligt i den tilhørende opgave på skolens it-platform*. Det er tilladt at skrive og tegne i hånden, og så aflevere et billede, som er konverteret til pdf.
#+reveal_html: </div>

